name: mfen
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.13
  - pytorch=1.10.1
  - tensorboardx=2.2
  - torchvision=0.11.2
  - numpy=1.21.5
  - tqdm=4.63.0
  # - cudatoolkit=11.3.1
  - pip
  - pip:
      - matplotlib>=3.3.0
      - opencv-python>=4.5.0
      - lpips>=0.1.4
      - fvcore>=0.1.5
      - Pillow>=8.0.0
